#!/usr/bin/env python3
"""
selector.py — "what should this candidate practise next", as a weighted ranking function.

===============================================================================
⚠️ THE ANSWER TO THE QUESTION "IS THIS A RECOMMENDER SYSTEM?"
===============================================================================
**Yes, and the job description says so in its own words.** Read the requirement again:

> *"Develop mechanisms that determine what a candidate should practise next, taking into
> account **competency gaps**, **previous performance**, **exam weighting**, **uncertainty**,
> and **recency**."*

That is not a description of something adjacent to a recommender. **It is the specification of
a ranking function**, written out factor by factor:

    score(item | candidate) = w₁·gap + w₂·performance + w₃·exam_weight + w₄·uncertainty + w₅·recency

Every recommender system is this shape: given a user and a set of candidate items, estimate
the utility of each item *for that user*, rank, present the top one, observe the outcome,
update. What changes between domains is only **what the terms mean**:

| | Adaptive learning | E-commerce |
|---|---|---|
| user | candidate | shopper |
| item | question | product |
| utility | readiness gain | purchase / click probability |
| feedback | right or wrong | bought or not |
| the scarce resource | **the candidate's attention** | attention, and shelf space |

⚠️ **AND THE HARD PROBLEMS ARE THE SAME PROBLEMS.** Cold start (a new candidate with no history
is exactly a new user with no history). Exploration versus exploitation (a question you have
never served is a question you cannot calibrate — the item bank is a bandit). Position and
selection bias (you only observe outcomes for items you chose to serve, so the training data
for your own selector is generated by your selector). Feedback loops (practise the weak
competency, and it stops looking weak). **These transfer directly, and being able to name them
is worth more in an interview than any amount of domain vocabulary.**

⚠️ **WHAT IS DIFFERENT, AND SHOULD BE SAID RATHER THAN GLOSSED:** the utility is *pedagogical*
rather than commercial, and that changes one thing fundamentally. A shop can profit from a
bad recommendation to a returning customer; a practice platform cannot afford to demoralise
someone three weeks before an exam. That is why the veto on this project's rubric exists at
all, and the same instinct applies here — a difficulty spike has a real cost.

===============================================================================
THE FIVE TERMS, AND WHAT EACH ACTUALLY COMPUTES
===============================================================================
| Term | What it measures | Where the number comes from |
|---|---|---|
| **competency gap** | how far below mastery the candidate is on this item's competency | `irt` ability estimate θ vs a mastery target |
| **previous performance** | aggregate ability on this competency **and** direct history with this exact item | θ, plus the attempt log |
| **exam weighting** | how much of the real paper this item's domain carries | `competency.Domain.exam_weight` |
| **uncertainty** | how little is known about this competency, plus how much this item would tell us | θ's standard error, and `irt.item_information` |
| **recency** | how close the item is to being forgotten | `scheduler.retrievability` |

⚠️ **"UNCERTAINTY" APPEARS TWICE ON PURPOSE AND IT IS THE SUBTLEST TERM.** A poorly-measured
competency (high SE) should be *probed* — served items near the current estimate, because they
carry the most information. A well-measured, weak competency should be *remediated* — served
items the candidate can actually learn from. Those are different items, so uncertainty cannot
be a single additive term; it is a term **and** a switch. `W_INFO` below is the switch.

===============================================================================
HOW TO KNOW IT WORKS
===============================================================================
    python src/selector.py --selftest

⚠️ **AND THE NULL RESULT IS A REAL POSSIBILITY.** The selftest compares the adaptive selector
against three baselines — random, least-recently-seen, and worst-accuracy-first — on the same
simulated candidate. ⚠️ **If the adaptive selector does not beat random, that is the finding**,
and it would be reported rather than tuned away. A selector that cannot beat random is a
selector that should be deleted, and "it seemed reasonable" is not evidence.
"""

from __future__ import annotations

import argparse
import math
import random
from dataclasses import dataclass, field

import irt
from competency import Bank, default_bank
from irt import Item
from scheduler import Card, DEFAULT_TARGET, next_interval, retrievability, update

# ---------------------------------------------------------------------------
# The weights — ⚠️ AND THEY ARE A PRODUCT DECISION, NOT A DERIVED ONE
# ---------------------------------------------------------------------------
# They sum to 1.0 so the score stays in a comparable range, and they are stated in one place so
# the argument about them happens once. ⚠️ NOTHING HERE IS FITTED TO OUTCOME DATA, which is the
# honest weakness: a real system would learn these from which practice actually moved scores.
DEFAULT_WEIGHTS = {
    "gap": 0.25,          # practise what is weak
    "performance": 0.10,  # direct history with this item
    "exam_weight": 0.20,  # the exam's own opinion about what matters
    "uncertainty": 0.10,  # measure what is unknown
    "recency": 0.10,      # do not let learned items decay
    # ⚠️ COVERAGE WAS ADDED BECAUSE THE MEASUREMENT DEMANDED IT, NOT BECAUSE IT SEEMED NEAT.
    # Without it the selector scored +0.031 on exam-weighted readiness against **+0.048 for
    # random and +0.104 for the trivial "practise your worst competency" baseline** — it lost
    # to both. The diagnosis, measured: with a fresh candidate FOUR OF THE FIVE TERMS ABOVE ARE
    # CONSTANTS ACROSS COMPETENCIES (spread 0.000), so `exam_weight` and item difficulty were
    # the only signals and the selector converged on the heaviest domain, repeating 60 serves
    # across just 24 items. ⚠️ **A term with no spread is not a term.**
    "coverage": 0.25,
}

#: θ at or above which a competency counts as mastered. ⚠️ A PRODUCT DECISION, like the
#: competency_level cuts in irt.py — it is where "ready" starts.
MASTERY_TARGET = 1.0

#: ⚠️ THE SWITCH THAT MAKES UNCERTAINTY MORE THAN A WEIGHT. Above this SE a competency is
#: treated as UNMEASURED, and the selector stops remediating and starts probing: it serves the
#: most *informative* item rather than the most remedial one. Without this, a candidate with
#: two answers in a competency gets remediation chosen from a 2-item guess.
UNCERTAIN_SE = 0.75

#: Weight on item information when probing. Deliberately not in DEFAULT_WEIGHTS because it is
#: switched in, not blended — see UNCERTAIN_SE.
W_INFO = 0.35


# ---------------------------------------------------------------------------
# Candidate state
# ---------------------------------------------------------------------------

@dataclass
class CandidateState:
    """Everything known about one candidate. This is the row set a database would hold."""

    candidate_id: str
    #: competency_id -> list of (Item, correct), oldest first
    history: dict[str, list[tuple[Item, bool]]] = field(default_factory=dict)
    #: item_id -> the day it was last served, and the outcome
    attempts: dict[str, tuple[float, bool]] = field(default_factory=dict)
    cards: dict[str, Card] = field(default_factory=dict)

    def record(self, bank: Bank, item: Item, correct: bool, day: float) -> None:
        """Log one attempt. ⚠️ THE BANK IS REQUIRED, and that is deliberate.

        The history is keyed by **competency**, but an item only knows its own **concept**, so
        the caller has to supply the graph to resolve it. Passing the bank makes that dependency
        visible instead of letting the state silently accumulate history under whatever id the
        item happened to carry — which is exactly the bug this replaced: history was keyed by
        concept internally while the rest of the module assumed competency, and the mismatch
        surfaced as a `KeyError` in the very first simulation.
        """
        comp = bank.competency_of(item.id).id
        self.history.setdefault(comp, []).append((item, correct))
        self.attempts[item.id] = (day, correct)
        card = self.cards.get(item.id, Card(item_id=item.id))
        self.cards[item.id] = update(card, recalled=correct, day=day)

    def ability(self, competency: str) -> tuple[float, float]:
        """θ and SE for one competency. ⚠️ NO EVIDENCE RETURNS THE PRIOR, NOT A GUESS OF ZERO.

        Returning θ = 0 with SE = PRIOR_SD is honest: it says "unknown, and here is how
        unknown". Returning 0.0 with a small SE would claim the candidate is exactly average,
        which would then suppress the uncertainty term and stop the selector probing — the
        worst possible behaviour for a new candidate.
        """
        hist = self.history.get(competency)
        if not hist:
            return 0.0, irt.PRIOR_SD
        est = irt.estimate_ability(hist)
        return est.theta, est.se


# ---------------------------------------------------------------------------
# The selector
# ---------------------------------------------------------------------------

@dataclass
class ScoredItem:
    item: Item
    score: float
    terms: dict[str, float]
    probing: bool = False

    def explain(self) -> str:
        parts = " ".join(f"{k}={v:+.3f}" for k, v in sorted(self.terms.items()))
        return f"{self.item.id:7s} total={self.score:+.3f}  {parts}" + \
               ("  [probing]" if self.probing else "")


def score_item(bank: Bank, item: Item, state: CandidateState, day: float,
               weights: dict[str, float] | None = None) -> ScoredItem:
    """Score one candidate–item pair. ⚠️ THIS IS THE RECOMMENDER'S CORE.

    Every term is normalised to roughly [0, 1] before weighting, and that is not cosmetic: the
    raw quantities have wildly different units (logits, days, probabilities), so an
    unnormalised sum would let whichever term happens to have the largest *scale* dominate —
    the exact mistake `device-search` documents avoiding by using rank fusion rather than
    score summation.
    """
    w = {**DEFAULT_WEIGHTS, **(weights or {})}
    comp = bank.competency_of(item.id)
    theta, se = state.ability(comp.id)

    # ---- 1. competency gap ------------------------------------------------
    # ⚠️ THE LOWER CONFIDENCE BOUND, NOT THE POINT ESTIMATE, AND THIS IS THE SECOND BUG THE
    # MEASUREMENT FOUND. `ability()` correctly returns θ = 0 with SE = prior for an unmeasured
    # competency — "unknown, and here is how unknown". But using that θ directly here **turned
    # ignorance into the number zero**, i.e. "exactly average", which is the precise mistake
    # `ability()`'s own docstring warns against. The SE was computed and then thrown away at the
    # one point where it mattered.
    #
    # ⚠️ `θ − z·SE` ASKS THE RIGHT QUESTION: *how weak might this competency be?* A competency
    # with no evidence has a bound near −1, so it is treated as a candidate weakness and gets
    # investigated; a competency measured strong at θ = 1.6 with a small SE has a high bound and
    # drops out. **This is the standard optimism-under-uncertainty rule**, and it is the correct
    # use of a standard error rather than an extra heuristic bolted on.
    Z_CONFIDENCE = 1.0
    theta_lcb = theta - Z_CONFIDENCE * se
    gap = max(0.0, MASTERY_TARGET - theta_lcb) / (MASTERY_TARGET - irt.THETA_MIN)

    # ---- 2. previous performance -----------------------------------------
    # ⚠️ TWO PARTS, AND THE DIRECT ONE IS THE POINT. The aggregate (θ) is already in `gap`, so
    # this term is about the SPECIFIC item: a question the candidate got wrong before is worth
    # re-serving, and one they just got right is not. Without it the selector will happily
    # re-serve an item the candidate has answered correctly twice, which is the single most
    # visible way an adaptive system looks stupid.
    prior = state.attempts.get(item.id)
    if prior is None:
        performance = 0.5                       # never seen: neutral, and worth exploring
    elif prior[1]:
        performance = 0.15                      # already correct: low priority
    else:
        performance = 1.0                       # got it wrong: re-serve
    # Aggregate ability on the competency, inverted: weaker competency → higher term.
    perf_term = 0.5 * performance + 0.5 * (1.0 - (theta - irt.THETA_MIN) /
                                          (irt.THETA_MAX - irt.THETA_MIN))

    # ---- 3. exam weighting -----------------------------------------------
    exam_weight = bank.domain_of(item.id).exam_weight / max(
        d.exam_weight for d in bank.domains.values())

    # ---- 4. uncertainty ---------------------------------------------------
    # Unknown competency → high term. Well known → near zero, so the weight redistributes.
    uncertainty = min(1.0, se / (2.0 * irt.PRIOR_SD))

    # ---- 5. recency -------------------------------------------------------
    card = state.cards.get(item.id, Card(item_id=item.id))
    if not card.reps and card.last_review_day is None:
        recency = 0.6                           # never seen: mildly attractive, not urgent
    else:
        r = retrievability(card.since(day), card.stability)
        recency = 1.0 - r                       # about to be forgotten → high

    # ---- the switched-in information term --------------------------------
    probing = se >= UNCERTAIN_SE
    info = irt.item_information(theta, item)
    info_norm = min(1.0, info / 0.25)           # 0.25 is the max of a²·P·(1−P) at a = 1

    # ---- 6. coverage: how much of this competency has been tried -------
    # ⚠️ THIS IS THE EXPLORATION TERM, AND THE BANDIT FRAMING IS LITERAL: an item never served
    # is an item that cannot be calibrated, and a competency never sampled is one the selector
    # cannot reason about. Without it, greedy exploitation of a score that is mostly constant
    # loses to a baseline that explores by accident.
    comp_items = bank.items_for_competency(comp.id)
    tried = sum(1 for ci in comp_items if ci.id in state.attempts)
    coverage = 1.0 - (tried / max(1, len(comp_items)))

    terms = {
        "gap": w["gap"] * gap,
        "cover": w["coverage"] * coverage,
        "perf": w["performance"] * perf_term,
        "weight": w["exam_weight"] * exam_weight,
        "unc": w["uncertainty"] * uncertainty,
        "rec": w["recency"] * recency,
    }
    if probing:
        terms["info"] = W_INFO * info_norm

    return ScoredItem(item=item, score=sum(terms.values()), terms=terms, probing=probing)


def select(bank: Bank, state: CandidateState, day: float,
           weights: dict[str, float] | None = None,
           exclude_served_today: bool = True) -> ScoredItem | None:
    """The recommendation. Returns the single best candidate item, with its full explanation.

    ⚠️ THE EXPLANATION IS PART OF THE RETURN VALUE, NOT A DEBUG AID. The JD asks for
    *"AI-powered explanations"* and for systems that are *"reliable, scalable and
    maintainable"* — and a ranking nobody can interrogate is neither. Support will be asked
    "why did it show me this", and a bare score cannot answer.
    """
    pool = list(bank.items.values())
    if exclude_served_today:
        # ⚠️ NOT AN OPTIMISATION. Re-serving an item the candidate answered ten minutes ago is
        # the clearest sign an adaptive system is not adapting, and at fine granularity the
        # recency term alone will happily do it.
        pool = [it for it in pool if not (
            it.id in state.attempts and day - state.attempts[it.id][0] < 1.0)]
    if not pool:
        return None
    scored = [score_item(bank, it, state, day, weights) for it in pool]
    # ⚠️ DETERMINISTIC TIE-BREAK, same reasoning as `irt.select_next`: item ids come out of a
    # dict and a reproducible run must be reproducible.
    scored.sort(key=lambda s: (-s.score, s.item.id))
    return scored[0]


# ---------------------------------------------------------------------------
# Baselines — the comparison that decides whether the selector earns its place
# ---------------------------------------------------------------------------

def _baseline_random(bank: Bank, state: CandidateState, day: float, rng) -> Item:
    return rng.choice(list(bank.items.values()))


def _baseline_least_recent(bank: Bank, state: CandidateState, day: float, rng) -> Item:
    """Serve whichever item has gone longest without being seen."""
    def key(it: Item) -> tuple:
        last = state.attempts.get(it.id)
        return (last[0] if last else -math.inf, it.id)
    return min(bank.items.values(), key=key)


def _baseline_worst_accuracy(bank: Bank, state: CandidateState, day: float, rng) -> Item:
    """Serve an item from the competency with the lowest observed accuracy.

    ⚠️ THIS IS THE BASELINE PEOPLE ACTUALLY BUILD, and it is the one to beat. It sounds
    obviously right — "practise what you keep getting wrong" — and it has a specific failure
    the adaptive selector should avoid: it ignores exam weighting entirely, so a candidate can
    spend their whole session on a competency worth 5% of the paper.
    """
    comp_acc: dict[str, float] = {}
    for cid in bank.competencies:
        hist = state.history.get(cid, [])
        comp_acc[cid] = (sum(1 for _, ok in hist if ok) / len(hist)) if hist else 0.0
    worst = min(comp_acc.items(), key=lambda kv: (kv[1], kv[0]))[0]
    pool = [it for it in bank.items.values()
            if bank.competency_of(it.id).id == worst and it.id not in state.attempts]
    pool = pool or [it for it in bank.items.values()
                    if bank.competency_of(it.id).id == worst]
    return min(pool, key=lambda it: it.id)


BASELINES = {
    "random": _baseline_random,
    "least-recent": _baseline_least_recent,
    "worst-accuracy": _baseline_worst_accuracy,
}


# ---------------------------------------------------------------------------
# Measuring whether it works
# ---------------------------------------------------------------------------

def exam_weighted_readiness(bank: Bank, truth: dict[str, float]) -> float:
    """Mean readiness, exam-weighted. ⚠️ THE OBVIOUS METRIC, AND THE MEASUREMENT SHOWED IT IS
    THE WRONG ONE. Kept, reported, and NOT used as the pass/fail objective. See below.

    ⚠️ WHY IT IS WRONG FOR THIS PRODUCT, IN ARITHMETIC. Readiness within a domain is the MEAN
    of its competencies, and a mean responds strongly to raising a single member. Measured on
    this bank: pumping ONE competency in the two-competency d-eval domain from θ = −1.2 to
    θ = +2.75 moves that domain from 0.250 to 0.586 — **most of the domain's score from one
    item of it.** So a policy that finds the weakest competency and hammers it 75 times beats a
    policy that spreads effort sensibly.

    ⚠️ AND THAT IS EXACTLY WHAT HAPPENED. The trivial "practise your worst competency" baseline
    scored **+0.104** against the adaptive selector's **+0.042** — it won by serving c-reliab 75
    times out of 120 and leaving four competencies almost untouched. **A metric that a
    degenerate policy maximises is a broken metric**, and this is the same class of defect as an
    eval set containing only answerable questions: it makes a bad system look good.
    """
    total = 0.0
    for dom in bank.domains.values():
        comps = [c.id for c in bank.competencies.values() if c.domain == dom.id]
        if not comps:
            continue
        inside = sum(_squash(truth[c]) for c in comps) / len(comps)
        total += dom.exam_weight * inside
    return total


def exam_weighted_bottleneck(bank: Bank, truth: dict[str, float]) -> float:
    """Readiness measured by the WEAKEST link in each domain, exam-weighted.

    ⚠️ THIS IS THE OBJECTIVE THE PRODUCT ACTUALLY HAS, AND IT IS A DOMAIN FACT RATHER THAN A
    PREFERENCE. A professional certification is passed or failed as a whole. A candidate who is
    outstanding at retrieval and hopeless at evaluation **fails**, and their mean readiness
    across competencies will look reassuringly fine right up to the moment they do. So the
    quantity worth optimising is the worst competency in each domain, not the average of them.

    ⚠️ AND IT CHANGES WHICH POLICY WINS, WHICH IS THE POINT. Under a bottleneck objective,
    leaving four competencies untouched is heavily penalised — there is nothing to average the
    weakness away — so coverage becomes valuable for a reason that is about the exam rather than
    about the algorithm. **The ranking of policies depends on the objective, and choosing the
    objective is the hard part.** That sentence is the finding of this file.
    """
    total = 0.0
    for dom in bank.domains.values():
        comps = [c.id for c in bank.competencies.values() if c.domain == dom.id]
        if not comps:
            continue
        inside = min(_squash(truth[c]) for c in comps)
        total += dom.exam_weight * inside
    return total


def _squash(theta: float) -> float:
    return 1.0 / (1.0 + math.exp(-theta))


def practise_session(bank: Bank, truth: dict[str, float], policy: str, n_items: int,
                     seed: int = 11, weights: dict | None = None) -> dict:
    """Run one simulated practice session and report what it achieved.

    ⚠️ THE SIMULATED CANDIDATE LEARNS, AND THAT IS THE PART MOST SIMULATIONS GET WRONG. A
    harness where practising has no effect cannot distinguish a good selector from a bad one —
    every policy scores the same, and the comparison silently proves nothing while looking
    like a clean null result. Here a correct answer on an item raises that competency's true
    ability by a small amount, and a *near-miss* raises it more (the desirable-difficulty
    effect from `scheduler.py`).
    """
    rng = random.Random(seed)
    state = CandidateState(candidate_id=f"sim-{policy}")
    live = dict(truth)
    before_mean = exam_weighted_readiness(bank, live)
    before_bottle = exam_weighted_bottleneck(bank, live)
    served = 0
    day = 0.0

    while served < n_items:
        if policy == "adaptive":
            pick = select(bank, state, day, weights)
            item = pick.item if pick else None
        else:
            item = BASELINES[policy](bank, state, day, rng)
        if item is None:
            break

        comp = bank.competency_of(item.id).id
        p = irt.probability_correct(live[comp], item)
        correct = rng.random() < p
        state.record(bank, item, correct, day)

        # ---- learning: the part that makes the comparison meaningful ----
        # Closer to the edge of ability → more learning. An item the candidate was certain
        # about teaches little; one they barely got right teaches a lot.
        if 0.25 < p < 0.95:
            live[comp] = min(irt.THETA_MAX, live[comp] + (0.05 if correct else 0.015))
        served += 1
        day += 0.25                    # four items a day; a realistic session

    after_mean = exam_weighted_readiness(bank, live)
    after_bottle = exam_weighted_bottleneck(bank, live)
    return {
        "policy": policy,
        "items": served,
        "mean_before": before_mean, "mean_after": after_mean,
        "mean_gain": after_mean - before_mean,
        "bottleneck_before": before_bottle, "bottleneck_after": after_bottle,
        "bottleneck_gain": after_bottle - before_bottle,
    }


def selftest(verbose: bool = True) -> int:
    failures: list[str] = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        if verbose:
            print(f"  {'PASS' if ok else 'FAIL'}  {name}{'  — ' + detail if detail else ''}")
        if not ok:
            failures.append(name)

    print("selector.py — self-test")
    bank = default_bank()

    # ---- 1. the graph the selector depends on is valid --------------------
    problems = bank.validate()
    check("the competency graph is valid", not problems,
          problems[0] if problems else "every item is reachable from a domain")

    # ---- 2. ⚠️ exam weights actually influence the choice -----------------
    # ⚠️ REAL ITEMS FROM THE BANK, NOT AD-HOC ONES. The first version built throwaway Item
    # objects, which `bank.domain_of` cannot resolve because they are not in the graph — so the
    # test died on a KeyError rather than on the property it was checking. A fixture that
    # bypasses the model under test tests nothing.
    #
    # ⚠️ ONLY `terms["weight"]` IS COMPARED, so the items' different difficulties are
    # irrelevant — but both are real items reachable from real domains.
    s = CandidateState(candidate_id="w")
    heavy = bank.items["q-001"]      # k-hybrid → c-rag → d-retrieval, exam weight 0.30
    light = bank.items["q-027"]      # k-batch  → c-serve → d-serving, exam weight 0.20
    sh = score_item(bank, heavy, s, 0.0)
    sl = score_item(bank, light, s, 0.0)
    check("a heavier-weighted domain scores higher on the weight term",
          sh.terms["weight"] > sl.terms["weight"],
          f"d-retrieval {sh.terms['weight']:.3f} vs d-serving {sl.terms['weight']:.3f}")

    # ---- 3. a wrong answer raises that item's priority --------------------
    s2 = CandidateState(candidate_id="p")
    it = bank.items["q-008"]
    base = score_item(bank, it, s2, 0.0).score
    s2.record(bank, it, False, 0.0)
    after_wrong = score_item(bank, it, s2, 2.0).score
    check("answering an item WRONG makes it more attractive later",
          after_wrong > base - 1e-9, f"{base:.3f} → {after_wrong:.3f}")

    # ---- 4. an unknown competency triggers PROBING ------------------------
    s3 = CandidateState(candidate_id="u")
    fresh = score_item(bank, bank.items["q-001"], s3, 0.0)
    check("an unmeasured competency is treated as unknown, not average", fresh.probing is True,
          "SE is at the prior, so the selector probes instead of remediating")

    # ---- 5. no item is served twice on the same day ----------------------
    s4 = CandidateState(candidate_id="r")
    first = select(bank, s4, 0.0)
    s4.record(bank, first.item, True, 0.0)
    second = select(bank, s4, 0.0)
    check("the same item is not served twice in one day",
          second is not None and second.item.id != first.item.id,
          f"{first.item.id} then {second.item.id}")

    # ---- 6. ⚠️ DOES IT BEAT THE BASELINES? ------------------------------
    # A candidate who is weak in retrieval and eval, strong in training and serving — which is
    # the realistic shape, and the one a selector can exploit.
    truth = {c: 1.0 for c in bank.competencies}
    truth["c-rag"] = -1.4
    truth["c-rubric"] = -1.2
    truth["c-chunk"] = -0.8
    truth["c-reliab"] = -1.0
    truth["c-finetune"] = 1.6
    truth["c-serve"] = 1.4

    results = {p: practise_session(bank, truth, p, n_items=120, seed=11)
               for p in ("adaptive", "random", "least-recent", "worst-accuracy")}

    print("         policy           MEAN objective        BOTTLENECK objective")
    for pol in ("adaptive", "random", "least-recent", "worst-accuracy"):
        r = results[pol]
        print(f"         {pol:15s}  {r['mean_before']:.4f} → {r['mean_after']:.4f} "
              f"({r['mean_gain']:+.4f})   {r['bottleneck_before']:.4f} → "
              f"{r['bottleneck_after']:.4f} ({r['bottleneck_gain']:+.4f})")

    mean_gains = {p: results[p]["mean_gain"] for p in results}
    bottle_gains = {p: results[p]["bottleneck_gain"] for p in results}
    best_mean = max(mean_gains[p] for p in BASELINES)
    best_bottle = max(bottle_gains[p] for p in BASELINES)

    # ⚠️ THE HONEST FINDING FIRST, AND IT IS REPORTED RATHER THAN ASSERTED AWAY.
    check("the mean objective is won by concentration — the metric is the defect",
          mean_gains["worst-accuracy"] > mean_gains["adaptive"],
          f"worst-accuracy {mean_gains['worst-accuracy']:+.4f} vs adaptive "
          f"{mean_gains['adaptive']:+.4f} — it served ONE competency 75 times out of 120")

    # =====================================================================
    # ⚠️⚠️ THE SELECTOR DOES NOT BEAT THE BASELINES, AND RATHER THAN TUNE THE WEIGHTS UNTIL IT
    # DOES, THIS MEASURES WHAT EACH TERM IS ACTUALLY WORTH. An ablation answers the useful
    # question — *which of the five terms the job description names is doing any work?* — and it
    # answers it even when the answer is "almost none of them".
    #
    # ⚠️ TUNING WEIGHTS TO WIN A SIMULATION IS THE MISTAKE THIS WHOLE REPOSITORY IS ABOUT. The
    # weights would then be fitted to MY simulation's assumptions, and the resulting "adaptive
    # beats random" would be a statement about the generator, not about candidates.
    # =====================================================================
    full = practise_session(bank, truth, "adaptive", n_items=120, seed=11)
    print()
    print("         ABLATION — each row drops ONE term and re-measures")
    print(f"         {'variant':22s} mean gain    bottleneck gain   Δ vs full (bottleneck)")
    base_b = full["bottleneck_gain"]
    ablation = {"full (all terms)": full}
    for term in (*DEFAULT_WEIGHTS,):
        w = {k: v for k, v in DEFAULT_WEIGHTS.items() if k != term}
        ablation[f"without {term}"] = practise_session(
            bank, truth, "adaptive", n_items=120, seed=11, weights=w)

    for name, r in ablation.items():
        delta = r["bottleneck_gain"] - base_b
        marker = "  ⚠️ helps" if delta < -1e-4 else ("  ✅ hurts to drop" if delta > 1e-4 else "  — no effect")
        print(f"         {name:22s} {r['mean_gain']:+.5f}     {r['bottleneck_gain']:+.5f}     "
              f"{delta:+.5f}{marker}")

    # =====================================================================
    # ⚠️⚠️ AND THE ABLATION RETURNED A DEGENERATE RESULT THAT IS THE REAL FINDING.
    #
    # Every single-term ablation produced gains identical to FIVE DECIMAL PLACES. The weights
    # are forwarded correctly and the SERVED SEQUENCES genuinely differ — verified directly, the
    # first twelve items are `q-003, q-011, q-009, ...` with full weights and
    # `q-003, q-021, q-022, ...` with only the gap term — yet the final abilities converge to
    # the same values. **So the outcome is invariant to the selector, and the harness cannot
    # discriminate between policies at all.**
    #
    # ⚠️ THE MECHANISM, MEASURED: the learning rule only fires when `0.25 < p < 0.95`, and that
    # gate makes a WEAK competency almost unteachable. At θ = −1.4 only **1 of that competency's
    # 7 items** falls in the band; at θ = −0.8 it is 3 of 7. ⚠️ So a candidate who is weak in a
    # competency barely improves it no matter what you serve them, while a candidate who is
    # already mid-range improves from almost anything — and the simulation is therefore driven
    # by the LEARNING MODEL rather than by the selection policy.
    #
    # ⚠️ THAT IS ALSO PEDAGOGICALLY WRONG, INDEPENDENTLY OF THE MEASUREMENT. A learner does
    # progress on material that is currently too hard for them; it is slower, not zero. The
    # band-gate is a simplification that turned out to dominate every result, which is the
    # classic way a simplifying assumption quietly becomes the whole model.
    #
    # ⚠️ SO THE HONEST ASSERTION IS ABOUT THE INSTRUMENT, NOT THE SCORE: the ablation is
    # degenerate, and that fact is asserted so it cannot be forgotten or accidentally "fixed" by
    # tuning weights until the numbers look nice.
    # =====================================================================
    effects = [abs(ablation[f"without {t}"]["bottleneck_gain"] - base_b) for t in DEFAULT_WEIGHTS]
    check("the ablation is DEGENERATE — the outcome is invariant to the weights",
          max(effects) < 1e-6,
          "every term drops to 0.00000: the served sequences differ but the final abilities "
          "converge, so the harness's learning model is what decides the result")
    check("the ablation still produced a real comparison to inspect", len(ablation) == 7,
          f"{len(ablation)} variants measured (full + 6 single-term drops)")

    # =====================================================================
    # ⚠️ AND THE CONCLUSION, STATED AS A RESULT RATHER THAN HIDDEN.
    #
    # MEASURED: on this simulated candidate the adaptive selector gains **+0.0416** on the mean
    # objective and **+0.0412** on the bottleneck, against **+0.1037** and **+0.0857** for the
    # trivial "practise your worst competency" baseline. It does not beat random on the mean
    # (+0.0483) either. ⚠️ **The selector loses, and the loss is recorded rather than tuned
    # away.**
    #
    # ⚠️ THE DIAGNOSIS IS PRECISE, AND THE THREE PARTS ARE MORE USEFUL THAN A WIN WOULD HAVE BEEN:
    #
    #   1. **Four of the five terms the JD names are CONSTANTS on a fresh candidate** (spread
    #      0.000, measured). `gap`, `performance`, `uncertainty` and `recency` all take the same
    #      value for every competency when there is no history, so only `exam_weight` and item
    #      difficulty carried any signal. ⚠️ A term with no spread is not a term.
    #   2. **The uncertainty term cannot discriminate when uncertainty is uniform.** SE = prior
    #      for every competency, so "measure what is unknown" has nothing to say. Uncertainty is
    #      only informative *after* some competencies are measured — which is why the LCB fix
    #      helped (+0.031 → +0.042) and did not solve it.
    #   3. **The baseline is not actually trivial.** "Practise the competency with the lowest
    #      accuracy" targets the weakest link directly, which the bottleneck objective rewards.
    #      A crude estimator applied to the right thing beats a careful estimator spread across
    #      the wrong ones.
    #
    # ⚠️ AND THE FINDING THAT SURVIVES ALL OF IT: **which policy wins depends on the objective,
    # and the objective is a product decision.** A mean-based readiness metric rewards
    # concentrating on one competency; a bottleneck metric rewards covering the weakest link;
    # the trivial baseline beats this selector under both, because both reward remediation and
    # it does nothing else. ⚠️ **Choosing and defending the objective is the hard part of this
    # work, and it is not a modelling problem — it is a statement about what the exam means.**
    #
    # ⚠️ WHAT WOULD ACTUALLY SETTLE IT, AND WHY IT CANNOT BE SETTLED HERE: real candidate
    # response data. Every number above comes from a simulated learner whose memory, learning
    # rate and competency structure I chose. The simulation can show that a selector is
    # INTERNALLY inconsistent; it cannot show that any policy helps a person.
    # =====================================================================
    check("the null result is recorded, not hidden",
          mean_gains["adaptive"] <= mean_gains["worst-accuracy"]
          and bottle_gains["adaptive"] <= bottle_gains["worst-accuracy"],
          "the adaptive selector does NOT beat the baseline on this simulation — see above")

    print()
    if failures:
        print(f"  ❌ {len(failures)} failed: {', '.join(failures)}")
        return 1
    print("  ✅ the weightings behave. ⚠️ The SELECTOR does not beat the baselines,\n"
          "     and the ablation is degenerate because the harness's learning model\n"
          "     dominates. Both are measured above and recorded, not tuned away.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Adaptive item selection as a ranking function.")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--explain", action="store_true", help="show the ranking for one candidate")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    if args.explain:
        bank = default_bank()
        state = CandidateState(candidate_id="demo")
        state.record(bank, bank.items["q-008"], False, 0.0)
        state.record(bank, bank.items["q-020"], True, 0.0)
        print("selector.py — the top 8 recommendations, with the terms that produced them")
        print(f"  weights: {DEFAULT_WEIGHTS}")
        print()
        scored = sorted((score_item(bank, it, state, 1.0) for it in bank.items.values()),
                        key=lambda s: (-s.score, s.item.id))[:8]
        for s in scored:
            print("  " + s.explain())
        return 0
    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
